http:
  host: "![rE715pd4eNr1KAKpVBCLLQ==]"
  port: "![bhu8dbNtT2g=]"

salesforce:
  user: "![5M4eWLlfIQuLBtXiHp/lNxcFoAnjdynT]"
  password: "![0xbx6wiNdpWDYUqE95kuDA==]"
  token: "![3ujAMssmWAFwm5+3r8e2A+adXBcqYXFUN+loVcGrvE0=]"
